### PR TITLE
Create file.txt

### PR DESCRIPTION
**Pull request by Domnicdev**
Hi shiva,I have uploaded my first version of my project source code ,so kindly review my code and update me if there is any change.

### CODE REVIEW

**Comment by Shiva-Rz** [comment]
Hi Domnic, I have reviewed your Backend code. 
In Review.java file there is an unwanted comment line, please remove those lines

**Comment by Domnicdev** [comment]
I have updated the file, is there anything else?

**Comment by Domnicdev** [comment]
> Hi Domnic, I have reviewed your Backend code. In Review.java file there is an unwanted comment line, please remove those lines

I have updated that file, is there any thing else

**Comment by Shiva-Rz** [comment]
In payment.controller file there is a method in comment,
and also in payment.repo file there is an unused method.

**Comment by Domnicdev** [comment]
Updated those files also shiva , anything other than that need to be updated

**Comment by Shiva-Rz** [comment]
That's it in the Backend part

**Comment by Shiva-Rz** [comment]
In Frontend part please remove the doctype and html tag in  admin.componenet. It's not required

**Comment by Shiva-Rz** [comment]
In the tenantcrud.html file you have used center tag. It will not be supported in the files. please remove it

**Comment by Domnicdev** [comment]
> In Frontend part please remove the doctype and html tag in admin.componenet. It's not required

Updated.

**Comment by Domnicdev** [comment]
Updated shiva, is there anything else ?

**Comment by Shiva-Rz** [comment]
That's it Domnic, Thank you

**Comment by Domnicdev** [comment]
Thanks a lot shiva

**Pull request merged**
